### ISSUE TITLE
Inclusivity expansion

### ISSUE THREAD

**Issue by katelovescode** [honestbleeps/engineering-manager-toolbox#1]
Under team performance, there's a section that reads:

```
Is the team modeling inclusive behavior?
- Are people delivering feedback to each other, even when it's difficult?
- Are people receiving feedback well?
- When was the last time your team delivered feedback to you about you? (If it has been a while, solicit some)
```

Inclusivity is modeled in all kinds of behavior, not just feedback.  It's important to assess performance based on all sorts of inclusive behavior.  Recommended reading: https://chelseatroy.com/2018/05/24/why-your-efforts-to-make-your-company-inclusive-arent-working/ - there's an evaluation rubric in there for individual performance

I also think it's important to evaluate team (but not individual) performance based on inclusive language, as well.  Does the team often use "he or she" in communications?  e.g. "Each engineer should make sure they get 3 approvals on his or her PR" <-- this is exclusionary towards non-binary folks.  Is the team as a whole considering this kind of messaging/language as they write and communicate to each other and to external teams?

Some teams might think, "But we don't have non-binary folks on our team!"
- You can't tell non-binary folks by looking at them.  Often people present toward a binary gender for safety reasons even if they're not binary.
- A non-binary person shouldn't have to out themselves to their team to be respected or given safety
- New folks to the team or folks outside the team also deserve the same consideration and respect
- Your team should set the example for inclusivity and hopefully it will spread outwards.

I'd like to request these concepts be added to team evaluation, org evaluation, and individual evaluation, thoughtfully.  The article linked above also links out to tons of really helpful resources so please rabbit hole on those for a while  🐰🕳

**Comment by katelovescode** [comment]
Oh, also if you end up doing this please link the post above as a resource *inside* the readme, I'd love for there to be a list of resources at the bottom of this.  Now that I mention it, I'm going to make that a PR.

**Comment by honestbleeps** [comment]
While I would never describe any document as "finished" when it comes to addressing inclusive behavior, I'm going to mark this as closed for now with some incremental/helpful stuff added in.

I definitely welcome more contributions, corrections, etc on this and all topics!
