### ISSUE TITLE
Looking for innovators which swear by this toolbox

### ISSUE THREAD

**Issue by wparad** [honestbleeps/engineering-manager-toolbox#3]
Not exactly sure this should be an issue, but I wasn't sure how else to post this. I'm looking to find those to connect with that not only invest time in the aspects this toolbox mentions, but also feel they are on the cutting edge of solving those problems.

Where do you discuss such issues and what tools do you use to improve?  Are there software/process MVPs out there that you would swear by? Is there a community you spend time focusing on, where do you go to get more information?

**Comment by honestbleeps** [comment]
Hi William,

I'd recommend [Engineering Managers Slack](https://engmanagers.github.io/) as a first start! It's the best and only resource I'm really aware of that fits what you're asking for.  I hope that helps!

I'll go ahead and close this issue, but don't take that as a request to stop responding. Just github housekeeping :-)

**Comment by wparad** [comment]
That is certainly one good place to find some, but I'm worried that it might actually be too wide of a list.  And are all of those people really innovators in engineering leadership?  Sure there are those that have experience or may be doing things that no one else is doing yet. What is the mark of an innovator in the leadership community?

**Comment by honestbleeps** [comment]
there are definitely some recognizable names in there, but if you're really, really wanting to only talk to specific folks at larger companies I think that's going to be hard to find. They're pressed for time and not always willing to spend it helping others.  There's a paid service called Plato that I've not actually tried out, but it seems to be closer to what you're looking for.

**Comment by wparad** [comment]
Company size or paradigms aren't exactly what I'm focused on. It is more about who is an innovator in tech leadership, and where do invest their time?  Who is their community, which helps them improve?  As a potential member, I'm looking for my fellow colleagues and where they frequent.  I've tried reddit and some different slack workspaces, but I'm not convinced that those are the only places to be.
